name: Cargo Test

on:
  workflow_run:
    workflows: ["Cargo Check"]
    types: 
      - completed

jobs:
  test:
    runs-on: 
      labels: movement-runner
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.CI_PAT }}

      - name: Setup
        uses: ./.github/actions/setup-linux-x86_64

      - name: Build and Test Subnet
        run: |
          cd ./m1
          cargo test

      - name: Update Badge
        run: |
          if [ $? -eq 0 ]; then
            sed -i 's/badge\/tests-[a-zA-Z]*/badge\/tests-Passing-brightgreen/g' README.md
          else
            sed -i 's/badge\/tests-[a-zA-Z]*/badge\/tests-Failing-red/g' README.md
          fi
        if: ${{ always() }}
